pmemchk

Allow user to run data collector only using '-C' option.

---

analyzer/optane/check_region_persistentmemorytype

Add check_region_persistentmemorytype rule

---

analyzer/optane/check_region_capacity

Fixed check_region_capacity

---

collector/collector

Adding Post-Processing 'ipmctl show -a' files

---

analyzer/optane/check_dimm_packagesparesavailable

Adding rule PackageSparesAvailable < 1

---

analyzer/optane/check_dimm_packagesparesavailable

Fixing Property variable scope issue in while statement

---

analyzer/optane/check_dimm_packagesparingcapable

Adding Rule PackageSparingCapable != 1

---

analyzer/optane/check_dimm_arsstatus

Adding Rule check_dimm_arsstatus

---

analyzer/optane/check_dimm_skuviolation

Adding Rule check_dimm_skuviolation

---

analyzer/optane/check_dimm_configurationstatus

Adding Rule check_dimm_configurationstatus

---

analyzer/optane/check_dimm_arsstatus
analyzer/optane/check_dimm_configurationstatus
analyzer/optane/check_dimm_packagesparesavailable
analyzer/optane/check_dimm_packagesparingcapable
analyzer/optane/check_dimm_packagesparingenabled
analyzer/optane/check_dimm_skuviolation
analyzer/optane/check_percentage_remaining

Skip tests when grep finds no data to process

---

analyzer/optane/check_dimm_memoryboostfeature

Adding Rule check_dimm_memoryboostfeature

---

analyzer/optane/check_masterpassphraseenabled

Added Rule check_masterpassphraseenabled

---

collector/collector
common/common

Adding progress bar feature

---

pmemchk

Adding (-l) to list analyzer rules and modules feature

---

pmemchk

Implement cxl cmd

---

analyzer/optane/check_dimm_thermalthrottlelosspercent

Adding rule check_dimm_thermalthrottlelosspercent

---

analyzer/optane/check_dimm_reservedcapacity

Reserved capacity

---

analyzer/optane/check_dimm_partnumber

Adding rule check_dimm_partnumber

---

analyzer/optane/check_dimm_thermalthrottlelosspercent

Fix bug in check_dimm_thermalthrottlelosspercent on Optane 200

---

analyzer/optane/check_dimm_Extended_Adr_Enabled
analyzer/optane/check_dimm_PpcExtendedAdrEnabled
analyzer/optane/check_dimm_air_dram_enabled
analyzer/optane/check_dimm_boot_status
analyzer/optane/check_dimm_overwrite_status
analyzer/optane/check_dimm_poision_error_injections_counter
analyzer/optane/check_dimm_show_goal
analyzer/optane/check_dimm_viral_policy
analyzer/optane/check_dimm_viral_state

Check goal

---

analyzer/optane/check_dimm_PpcExtendedAdrEnabled

check_dimm_PpcExtendedAdrEnabled

---

analyzer/optane/check_dimm_Extended_Adr_Enabled
analyzer/optane/check_dimm_PpcExtendedAdrEnabled

Extended adr enabled

---

analyzer/optane/check_dimm_Extended_Adr_Enabled
analyzer/optane/check_dimm_PpcExtendedAdrEnabled
analyzer/optane/check_dimm_viral_policy

Viral policy

---

analyzer/optane/check_dimm_Extended_Adr_Enabled
analyzer/optane/check_dimm_PpcExtendedAdrEnabled
analyzer/optane/check_dimm_viral_policy
analyzer/optane/check_dimm_viral_state

Viral state

---

analyzer/optane/check_dimm_Extended_Adr_Enabled
analyzer/optane/check_dimm_PpcExtendedAdrEnabled
analyzer/optane/check_dimm_air_dram_enabled
analyzer/optane/check_dimm_viral_policy
analyzer/optane/check_dimm_viral_state

Air dram enabled

---

analyzer/optane/check_dimm_Extended_Adr_Enabled
analyzer/optane/check_dimm_PpcExtendedAdrEnabled
analyzer/optane/check_dimm_air_dram_enabled
analyzer/optane/check_dimm_poision_error_injections_counter
analyzer/optane/check_dimm_viral_policy
analyzer/optane/check_dimm_viral_state

Posion error injections counter

---

analyzer/optane/check_dimm_Extended_Adr_Enabled
analyzer/optane/check_dimm_PpcExtendedAdrEnabled
analyzer/optane/check_dimm_air_dram_enabled
analyzer/optane/check_dimm_boot_status
analyzer/optane/check_dimm_poision_error_injections_counter
analyzer/optane/check_dimm_viral_policy
analyzer/optane/check_dimm_viral_state

Boot status

---

analyzer/optane/check_dimm_Extended_Adr_Enabled
analyzer/optane/check_dimm_PpcExtendedAdrEnabled
analyzer/optane/check_dimm_air_dram_enabled
analyzer/optane/check_dimm_boot_status
analyzer/optane/check_dimm_overwrite_status
analyzer/optane/check_dimm_poision_error_injections_counter
analyzer/optane/check_dimm_viral_policy
analyzer/optane/check_dimm_viral_state

Overwrite status

---

analyzer/optane/check_dimm_error_injection_enabled

error injection enabled

---

collector/collector
collector/modules/collect_commands
collector/modules/collect_files
collector/modules/cxl
collector/modules/ipmctl
collector/modules/ndctl

Separate monolithic collector into modules

---

collector/modules/daxctl
pmemchk

Add daxctl collector module

---

collector/modules/cxl
collector/modules/ipmctl
collector/modules/ndctl

Run collector modules only if the command(s) are found

---

pmemchk

Add daxctl to verify_cmds()

---

collector/modules/ipmctl

[ipmctl collector module] Execute debug verbose command on failure

---

collector/modules/collect_commands
collector/modules/collect_files

[Collector] Collect more files and commands

---

analyzer/optane/check_dimm_firmware_error_count

[Optane Rule] Add check_dimm_firmware_error_count

---

pmemchk

Add check for Bash >= 4.0.0

---

analyzer/linux/full_file_system

Added analyzer/linux/full_file_system rule

---

analyzer/analyzer

Add REPORT_COUNT_CRITICAL and STR_CRITICAL message types

---

analyzer/analyzer
pmemchk

Add SKIPPED status messages

---

analyzer/linux/memmap

Adding analyzer/linux/memmap
